version: 1
update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: monthly
    commit_message:
      prefix: fix
      prefix_development: chore
      include_scope: true
