name: build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.16, 1.17 ]

    steps:
      - name: Check-out
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}

      - name: Download and check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Test
        run: go test -v -race ./...
